# Generated by Django 4.2.2 on 2024-11-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaryzation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('---', '---'), ('Автомобілі', 'Автомобілі'), ('Меблі', 'Меблі'), ('Будівлі', 'Будівлі'), ('Орг.техніка', 'Орг.техніка'), ('Периферія', 'Периферія'), ('Ноутбуки та ПК', 'Ноутбуки та ПК'), ('Смартфони та планшети', 'Смартфони та планшети'), ('Складське обладнання', 'Складське обладнання'), ('Предмети інтерєру', 'Предмети інтерєру')], default='---', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('inv_numb', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=500)),
                ('responsible', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('date_of_purchase', models.DateField(blank=True, default=None, null=True)),
                ('market_price', models.PositiveIntegerField(default=0)),
                ('date_of_registration', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
