# Generated by Django 4.2.2 on 2024-12-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaryzation', '0002_alter_inventaryzation_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaryzation',
            name='description',
            field=models.TextField(blank=True, default='-'),
        ),
    ]
