# Generated by Django 4.2.2 on 2025-01-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaryzation', '0004_archive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archive',
            new_name='ArchiveUtil',
        ),
    ]
