# Generated by Django 4.2.2 on 2025-01-09 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaryzation', '0007_rename_date_oeration_jurnal_date_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('data_create', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='inventaryzation',
            name='location',
            field=models.CharField(choices=[('Академія (Київ)', 'Академія (Київ)'), ('Магазин Рівер Мол', 'Магазин Рівер Мол'), ('Київський офіс', 'Київський офіс'), ('Іріс (магазин Іріс, Шевченка 390)', 'Іріс (магазин Іріс, Шевченка 390)'), ('Магазин Дашкевича 19', 'Магазин Дашкевича 19'), ('Магазин Сумгаїтська 39', 'Магазин Сумгаїтська 39'), ("Черкаський офіс (каб. Сиром'ятникової)", "Черкаський офіс (каб. Сиром'ятникової)"), ('Черкаський офіс (конференц зала+коридор у підвалі)', 'Черкаський офіс (конференц зала+коридор у підвалі)'), ('Черкаський офіс (каб. Системного адміністратора)', 'Черкаський офіс (каб. Системного адміністратора)'), ('Черкаський офіс (каб. СБ)', 'Черкаський офіс (каб. СБ)'), ('Черкаський офіс (каб. Бухгалтерії)', 'Черкаський офіс (каб. Бухгалтерії)'), ('Черкаський офіс (кухня+кімната відпочинку)', 'Черкаський офіс (кухня+кімната відпочинку)'), ('Черкаський офіс (каб. операторів)', 'Черкаський офіс (каб. операторів)'), ('Черкаський офіс (серверна)', 'Черкаський офіс (серверна)'), ('Основний склад (Давінес, Олвейз)', 'Основний склад (Давінес, Олвейз)'), ('Основний склад (Інструменти, Барба Італіано)', 'Основний склад (Інструменти, Барба Італіано)'), ('Склад митниця', 'Склад митниця'), ('Черкаський офіс (каб. Директорів)', 'Черкаський офіс (каб. Директорів)')], max_length=500),
        ),
        migrations.AddField(
            model_name='jurnal',
            name='act_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventaryzation.act'),
        ),
    ]
