# Generated by Django 4.2.2 on 2025-01-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaryzation', '0008_act_alter_inventaryzation_location_jurnal_act_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarNumberTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='act',
            name='file',
            field=models.FileField(upload_to='acts'),
        ),
    ]
