# Generated by Django 4.2.2 on 2025-01-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaryzation', '0009_inventarnumbertemp_alter_act_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnal',
            name='autor',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
