# Generated by Django 4.2.2 on 2025-01-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaryzation', '0010_jurnal_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnal',
            name='item',
            field=models.JSONField(),
        ),
    ]
