# Generated by Django 4.2.2 on 2023-07-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_location_mark_alter_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='mark',
        ),
    ]
