# Generated by Django 4.2.2 on 2023-07-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_remove_location_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='marker',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
