# Generated by Django 4.2.2 on 2023-08-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0005_alter_item_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_of_decommissioned',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
