# Generated by Django 4.2.2 on 2023-09-26 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0006_item_date_of_decommissioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='obj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='invent.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='worker',
            field=models.ManyToManyField(blank=True, default=None, to='invent.worker'),
        ),
    ]
