# Generated by Django 4.2.2 on 2023-10-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0007_history_obj_alter_item_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_decommissioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_reserve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='worker',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to=2, to='invent.worker'),
        ),
    ]
