# Generated by Django 4.2.2 on 2023-10-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0009_alter_location_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='marker',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
