# Generated by Django 4.2.2 on 2023-10-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0010_alter_location_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='worker',
            field=models.ManyToManyField(blank=True, default=None, to='invent.worker'),
        ),
    ]
