# Generated by Django 4.2.2 on 2023-12-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0011_alter_item_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='marker',
            field=models.CharField(default=None, help_text='#shop, sklad ...', max_length=10, null=True),
        ),
    ]
