# Generated by Django 4.2.2 on 2023-12-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0012_alter_location_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='marker',
            field=models.CharField(default=None, help_text='shop, sklad ...', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='office, plazma, rivermall, salon_LH2 ....', max_length=50),
        ),
    ]
