# Generated by Django 4.2.2 on 2024-10-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0013_alter_location_marker_alter_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaryzation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('0', '-'), ('1', 'Автомобілі'), ('2', 'Меблі'), ('3', 'Будівлі'), ('4', 'Орг.техніка'), ('5', 'Периферія'), ('6', "Ноутбуки та комп'ютери"), ('7', 'Смартфони та планшети'), ('8', 'Складське обладнання'), ('9', 'Предмети інтерєру')], default='0', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('inv_numb', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=500)),
                ('responsible', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(blank=True)),
                ('date_of_purchase', models.DateField(blank=True)),
                ('market_price', models.PositiveIntegerField(default='-')),
                ('date_of_registration', models.DateField(default='-')),
            ],
        ),
    ]
