# Generated by Django 4.2.2 on 2024-10-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0014_inventaryzation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaryzation',
            name='date_of_purchase',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inventaryzation',
            name='date_of_registration',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inventaryzation',
            name='group',
            field=models.CharField(choices=[('0', '---'), ('1', 'Автомобілі'), ('2', 'Меблі'), ('3', 'Будівлі'), ('4', 'Орг.техніка'), ('5', 'Периферія'), ('6', "Ноутбуки та комп'ютери"), ('7', 'Смартфони та планшети'), ('8', 'Складське обладнання'), ('9', 'Предмети інтерєру')], default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventaryzation',
            name='market_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventaryzation',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
