# Generated by Django 4.2.2 on 2024-10-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0017_alter_inventaryzation_date_of_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaryzation',
            name='date_of_purchase',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inventaryzation',
            name='date_of_registration',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
