# Generated by Django 4.2.2 on 2024-10-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0019_downloadfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadfiles',
            name='name',
        ),
    ]
