# Generated by Django 4.2.2 on 2024-11-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0021_delete_downloadfiles_alter_inventaryzation_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventaryzation',
        ),
    ]
